import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ProviderRedux } from "./providers/Provider";
import PostProvider from "./learn-context/context/PostContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostProvider>
          {children}
          {/* <div>
            <ProviderRedux>{children}</ProviderRedux>
          </div> */}
        </PostProvider>
      </body>
    </html>
  );
}
